name: Daily Database Backup

on:
  schedule:
    # Her gün saat 02:00'da çalış (UTC)
    - cron: '0 2 * * *'
  workflow_dispatch: # Manuel çalıştırma

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        
    - name: Create backup directory
      run: mkdir -p backups
      
    - name: Backup database
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        # Backup filename with timestamp
        BACKUP_FILE="backup_$(date +%Y%m%d_%H%M%S).sql"
        
        # Create SQL dump
        pg_dump "$DATABASE_URL" > "backups/$BACKUP_FILE"
        
        # Compress backup
        gzip "backups/$BACKUP_FILE"
        
        echo "Backup created: backups/$BACKUP_FILE.gz"
        
    - name: Upload to GitHub Releases
      uses: actions/upload-artifact@v4
      with:
        name: database-backup-${{ github.run_number }}
        path: backups/
        retention-days: 30
        
    - name: Upload to Cloud Storage (Optional)
      run: |
        # Cloud storage upload options
        echo "Backup completed successfully!"
        echo "Upload to cloud storage can be configured here"
        echo "Options: Google Drive, AWS S3, Dropbox, etc."
